# Generated by Django 4.2.4 on 2023-09-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views_by',
            field=models.IntegerField(default=0),
        ),
    ]
